<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-BNIRTNQ" failures="1" tests="4" name="Test" time="51.191" errors="0" timestamp="2023-01-09T19:40:05 IST">
  <testcase classname="com.sauceDemo.TestPackage.TC01_TestClass_VerifyLoginFunctionality" name="verifyLoginFunctionality" time="0.043"/>
  <testcase classname="com.sauceDemo.TestPackage.TC02_TestClass_VerifyLogOutFunctionality" name="verifyLogOutFunctionality" time="0.81"/>
  <testcase classname="com.sauceDemo.TestPackage.TC03_TestClass_VerifyBagProductAddTOCartFunctionality" name="verifyBagProductAddTOCartFunctionality" time="0.52"/>
  <testcase classname="com.sauceDemo.TestPackage.TC04_TestClass_VerifyAllProductsAddToCartFunctionality" name="verifyAllProductsAddToCartFunctionality" time="0.779">
    <failure type="java.lang.AssertionError" message="expected [6] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [3]
at com.sauceDemo.TestPackage.TC04_TestClass_VerifyAllProductsAddToCartFunctionality.verifyAllProductsAddToCartFunctionality(TC04_TestClass_VerifyAllProductsAddToCartFunctionality.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyAllProductsAddToCartFunctionality -->
</testsuite> <!-- Test -->
